-- 실습과제 8-1
SELECT NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM LOANS
    WHERE BRANCH_ID IN (
        SELECT BRANCH_ID
        FROM BRANCHES
        WHERE LOCATION = 'Location 1'));
        
-- 실습과제 8-2
SELECT TRANSACTION_ID
FROM TRANSACTIONS
WHERE ACCOUNT_ID IN (
    SELECT ACCOUNT_ID
    FROM ACCOUNTS
    WHERE CUSTOMER_ID = 100);
    
-- 실습과제 8-3    
SELECT CUSTOMER_ID, ACCOUNT_ID
FROM ACCOUNTS A
WHERE A.BALANCE = (
    SELECT MAX(BALANCE)
    FROM ACCOUNTS
    WHERE CUSTOMER_ID = A.CUSTOMER_ID);
