-- 실습과제 9-1
SELECT CUSTOMER_ID FROM CUSTOMERS
MINUS
SELECT CUSTOMER_ID FROM LOANS;

-- 실습과제 9-2
SELECT ACCOUNT_ID FROM TRANSACTIONS
INTERSECT
SELECT ACCOUNT_ID FROM ACCOUNTS;
    
-- 실습과제 9-3
SELECT BRANCH_ID FROM BRANCHES
MINUS
SELECT BRANCH_ID FROM LOANS;
