CREATE TABLE "USER" (
    IDUSER       NUMBER(10)      NOT NULL,
    NAME         VARCHAR2(50 CHAR),
    AGE          NUMBER(3),
    GENDER       VARCHAR2(20 CHAR),
    ADDRESS      VARCHAR2(100 CHAR),
    EMAIL        VARCHAR2(50 CHAR),
    PHONE        VARCHAR2(20 CHAR),
    PASSWORD     VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER PRIMARY KEY (IDUSER)
);
CREATE TABLE BANK (
    IDBANK   NUMBER(10)       NOT NULL,
    NAME     VARCHAR2(10 CHAR) NOT NULL,
    CONSTRAINT PK_BANK PRIMARY KEY (IDBANK)
);
CREATE TABLE ACCOUNT (
    IDACCOUNT      NUMBER(10)       NOT NULL,
    IDBANK         NUMBER(10)       NOT NULL,
    BALANCE        NUMBER(15)       DEFAULT 0,
    ACCOUNTNUMBER  VARCHAR2(20 CHAR),
    CREATEDATE     DATE             DEFAULT SYSDATE,
    PW             NUMBER(10),
    ISDORMANT      NUMBER(1)        DEFAULT 0,  -- 0: 사용중, 1: 휴면
    USER_IDUSER    NUMBER(10)       NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (IDACCOUNT),
    CONSTRAINT FK_ACCOUNT_BANK FOREIGN KEY (IDBANK)
        REFERENCES BANK(IDBANK),
    CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_IDUSER)
        REFERENCES "USER"(IDUSER)
);
CREATE TABLE TRANSMISSION (
    IDTRANSACTION     NUMBER(10)     NOT NULL,
    ACCOUNT_IDACCOUNT NUMBER(10)     NOT NULL,
    ACCOUNT_IDBANK    NUMBER(10),
    AMOUNT            NUMBER(15),
    "DATE"            DATE           DEFAULT SYSDATE,
    ISUPDATE          NUMBER(1)      DEFAULT 0,  -- 0: 일반, 1: 정정 또는 업데이트
    BALANCE           NUMBER(15),
    CONSTRAINT PK_TRANSMISSION PRIMARY KEY (IDTRANSACTION),
    CONSTRAINT FK_TRANSMISSION_ACCOUNT FOREIGN KEY (ACCOUNT_IDACCOUNT)
        REFERENCES ACCOUNT(IDACCOUNT),
    CONSTRAINT FK_TRANSMISSION_BANK FOREIGN KEY (ACCOUNT_IDBANK)
        REFERENCES BANK(IDBANK)
);
CREATE TABLE CARD (
    IDCARD            NUMBER(10)       NOT NULL,
    NAMECARD          VARCHAR2(50 CHAR),
    ACCOUNT_IDACCOUNT NUMBER(10),
    ISTRANSPORTATION  NUMBER(1)        DEFAULT 0,  -- 0: 일반카드, 1: 교통기능포함
    ISCHECK           NUMBER(1)        DEFAULT 0,  -- 0: 신용카드, 1: 체크카드
    IDBANK2           NUMBER(10),
    CONSTRAINT PK_CARD PRIMARY KEY (IDCARD),
    CONSTRAINT FK_CARD_ACCOUNT FOREIGN KEY (ACCOUNT_IDACCOUNT)
        REFERENCES ACCOUNT(IDACCOUNT),
    CONSTRAINT FK_CARD_BANK2 FOREIGN KEY (IDBANK2)
        REFERENCES BANK(IDBANK)
);
CREATE TABLE CARD_TRANSACTION (
    IDTRANSACTION   NUMBER(10)     NOT NULL,
    CARD_IDCARD     NUMBER(10)     NOT NULL,
    "DATE"          DATE           DEFAULT SYSDATE,
    TRANSACTIONTIME DATE,
    AMOUNT          NUMBER(15),
    IDBANK2         NUMBER(10),
    COMPANY_IDCOMPANY NUMBER(10),
    CONSTRAINT PK_CARD_TRANSACTION PRIMARY KEY (IDTRANSACTION),
    CONSTRAINT FK_CARD_TRANSACTION_CARD FOREIGN KEY (CARD_IDCARD)
        REFERENCES CARD(IDCARD),
    CONSTRAINT FK_CARD_TRANSACTION_BANK2 FOREIGN KEY (IDBANK2)
        REFERENCES BANK(IDBANK2),  -- 또는 BANK(IDBANK)로 수정 필요
    CONSTRAINT FK_CARD_TRANSACTION_COMPANY FOREIGN KEY (COMPANY_IDCOMPANY)
        REFERENCES COMPANY(IDCOMPANY)
);
CREATE TABLE COMPANY (
    IDCOMPANY     NUMBER(10)       NOT NULL,
    LOCATION      VARCHAR2(50 CHAR),
    CLASSCOMPANY  VARCHAR2(50 CHAR),
    NAMECOMPANY   VARCHAR2(50 CHAR),
    CONSTRAINT PK_COMPANY PRIMARY KEY (IDCOMPANY)
);
CREATE TABLE PRODUCT (
    IDPRODUCT       NUMBER(10)       NOT NULL,
    NAME            VARCHAR2(50 CHAR),
    FEATURE         VARCHAR2(255 CHAR),
    CATEGORY        VARCHAR2(255 CHAR),
    PRODUCTPERIOD   VARCHAR2(100 CHAR),
    PRODUCTCUSTOMER VARCHAR2(255 CHAR),
    PRODUCTINFO     VARCHAR2(255 CHAR),
    "CONDITION"     VARCHAR2(255 CHAR),
    CAUTION         VARCHAR2(255 CHAR),
    CREATEDATE      DATE   DEFAULT SYSDATE,
    UPDATEDATE      DATE,
    DELETEDATE      DATE,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (IDPRODUCT)
);
CREATE TABLE ISPRODUCT (
    IDISPRODUCT  NUMBER(10) NOT NULL,
    USER_IDUSER  NUMBER(10) NOT NULL,
    PRODUCT_IDPRODUCT NUMBER(10) NOT NULL,
    CONSTRAINT PK_ISPRODUCT PRIMARY KEY (IDISPRODUCT),
    CONSTRAINT FK_ISPRODUCT_USER FOREIGN KEY (USER_IDUSER)
        REFERENCES "USER"(IDUSER),
    CONSTRAINT FK_ISPRODUCT_PRODUCT FOREIGN KEY (PRODUCT_IDPRODUCT)
        REFERENCES PRODUCT(IDPRODUCT)
);
CREATE TABLE SURVEY (
    IDSURVEY          NUMBER(10)       NOT NULL,
    RESULT            VARCHAR2(255 CHAR),
    CREATEDATE        DATE  DEFAULT SYSDATE,
    UPDATEDATE        DATE,
    DELETEDATE        DATE,
    PRODUCT_IDPRODUCT NUMBER(10),
    IDUSER            NUMBER(10),
    CONSTRAINT PK_SURVEY PRIMARY KEY (IDSURVEY),
    CONSTRAINT FK_SURVEY_PRODUCT FOREIGN KEY (PRODUCT_IDPRODUCT)
        REFERENCES PRODUCT(IDPRODUCT),
    CONSTRAINT FK_SURVEY_USER FOREIGN KEY (IDUSER)
        REFERENCES "USER"(IDUSER)
);
CREATE TABLE PRODUCTRATE (
    IDPRODUCT  NUMBER(10)       NOT NULL,
    MAXRATE    NUMBER(5,2),     -- 예: 99.99 형식
    MINRATE    NUMBER(5,2),
    TYPE       VARCHAR2(50 CHAR),
    CONSTRAINT PK_PRODUCTRATE PRIMARY KEY (IDPRODUCT),
    CONSTRAINT FK_PRODUCTRATE_PRODUCT FOREIGN KEY (IDPRODUCT)
        REFERENCES PRODUCT(IDPRODUCT)
);
