-- 실습10-1
-- 거래 테이블에서 계좌별 누적 거래 급액을 계산
SELECT ACCOUNT_ID, TRANSACTION_ID, AMOUNT,
    SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID
    ORDER BY TRANSACTION_DATE
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
    AS CUM_AMOUNT
FROM TRANSACTIONS;

-- 실습10-2
-- 거래 테이블과 계좌별 최고 거래 금액을 출력하시오
SELECT ACCOUNT_ID, TRANSACTION_ID, AMOUNT,
    MAX(AMOUNT) OVER (PARTITION BY ACCOUNT_ID)
    AS MAX_AMOUNT
FROM TRANSACTIONS;

-- 실습10-3
-- 대출 테이블에서 지점별 누적 대출 금액을 계산하시오
SELECT BRANCH_ID, LOAN_ID, AMOUNT,
    SUM(AMOUNT) OVER (PARTITION BY BRANCH_ID
    ORDER BY LOAN_DATE
    BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
    AS BRANCH_CUM_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED';

-- 실습10-4
-- 계좌 테이블에서 고객별 평균 잔액을 계산하시요 (반올림하여 소수점 둘째 자리까지 출력)
SELECT CUSTOMER_ID, ACCOUNT_ID, BALANCE,ROUND(
    AVG(BALANCE) OVER (PARTITION BY CUSTOMER_ID), 2)
    AS AVG_BALANCE
FROM ACCOUNTS;
